---
title: "**GitHub**"
author: "dgonzalez"
subtitle: "**Rstudio**" 
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Configuración**

Para configurar Git y GitHub para su utulización debemos seguir los siguientes pasos

## Paso 1

Instalar git en nuestro computador ( para linux git ya está instalado)

## Paso 2

Configurar git en nuestro computador, para ello abrimos la terminal

~~~
$ git config user.name "Nombre Apellido"
$ git config user.email "usuario@gmail.com"
~~~

## Paso 3

Se verifica que tengamos activas las claves ssh
~~~
$ ls -al ~/.ssh
~~~

## Paso 4

Se actualiza el computador
~~~
$ sudo apt-get update
~~~

## Paso 5

Se debe copiar nuestra clave pública SSH en  GitHub , para lo cual abrimos el portal :

Setting / SSH and GPG keys
New SSH key

Adicionamos un nombre a la clave
Copiamos en el espacio la clave SSH que se generó en pc

## Paso 6

El siguiente procedimiento muestra el codigo Agent pid para ser adicionado

~~~
$ eval "$(ssh-agent -s)
Agent pid 12345
~~~

## Paso 7

Finalmente se adiciona este id 

~~~
$ ssh-add -K /home/@@@/.shh/id_rsa
Enter PIN for authenticador : 1234
~~~

LISTO para clonar y hacer commit y push

# **Clonar repositorio** 

Para clonar un repositorio se copia desde GitHub la URL SSH (git@github.com:dgonzalez80/ayudas.io.git) y se adiciona a la orden *git clone*

~~~
$ git clone git@github.com:dgonzalez80/ayudas.io.git
~~~

# **Actualizar repositorio**

Para actualizar un repositorio se corre el siguiente código

~~~
$ git add .
$ git commit -m "mensaje sobre cambios"
$ git push
~~~








